### ISSUE TITLE
Re-export `Coordinate`

### ISSUE THREAD

**Issue by maciejkula** [georust/rust-geohash#18]
Would you consider re-exporting `Coordinate`? The way things stand now, users of this crate also need to explicitly import `geo`.

(Edit: in which case it's down to the user to explicitly co-ordinate the versions of `Coordinate` between `geo`, and `geohash`: using `geohash` with `geo 0.8.0` doesn't work.)

**Comment by frewsxcv** [comment]
potentially relevant rust-geo pull request: https://github.com/georust/rust-geo/pull/201

**Comment by maciejkula** [comment]
It is relevant but I'm not sure it's a solution: I _think_ it would still require manual version co-ordination.

**Comment by frewsxcv** [comment]
done in https://github.com/georust/rust-geohash/pull/19
