### ISSUE TITLE
expected struct `geo::types::Coordinate`, found struct `geo_types::Coordinate`

### ISSUE THREAD

**Issue by adleroliveira** [georust/rust-geohash#24]
I don't know if I'm doing something wrong, but upon importing the crate geo_types and try and use geohash I get this error when trying to use the encode function.

expected struct `geo::types::Coordinate`, found struct `geo_types::Coordinate`

**Comment by adleroliveira** [comment]
I changed the dependency from geo_types to just geo and the error changed to:

expected struct `geo::types::Coordinate`, found struct `geo::Coordinate`

**Comment by frewsxcv** [comment]
there's probably a version mismatch. what's the version of `geo` in your Cargo.lock file?

**Comment by frewsxcv** [comment]
hm. can you paste any of the code your working on? or maybe just the section of code you're working with?
