### ISSUE TITLE
Crate causes errors

### ISSUE THREAD

**Issue by tsloughter** [georust/rust-geohash#6]
When using the latest published crate `0.2.3` building the example fails complaining that there are no functions `encode` or `decode`. Using `geohash = { git = "https://github.com/georust/rust-geohash.git" }` works fine. So I suspect a new version simply needs to be published to cargo?

**Comment by frewsxcv** [comment]
@sunng87 is the owner of package on crates.io, so they will need to publish a new version if this is the case. @sunng87 if you want, you can add the @georust organization as an Owner of the package on crates.io, though that's up to you

**Comment by sunng87** [comment]
@tsloughter I just released a new version on crates.io, could you please check if it works for you? 

@frewsxcv Thanks for the tip. Just added @georust/core team as owner of the crate.

**Comment by frewsxcv** [comment]
Thanks @sunng87!

**Comment by sunng87** [comment]
Seems the `rand` crate is broken on latest nightly (2016 nightlies break a lot of stuff). Since it's a dev-dependency, it should not affect your application.

**Comment by tsloughter** [comment]
Thanks, 0.2.4 works!
